const express = require('express')
const router = express.Router()
const isAuth=require('../middleware/is-auth')
const shopController=require('../controllers/shop_controller')
router.get('/',shopController.getIndex)
router.get('/products',shopController.getProducts)
router.get('/products/:productId',shopController.getProductDeatail)
router.post('/cart', isAuth,shopController.postCart)
router.get('/cart', isAuth,shopController.getCart)
router.post('/cartDelete', isAuth,shopController.postCartDeleteProducts)
router.post('/createOrder', isAuth,shopController.postOrder)
router.get('/orders', isAuth,shopController.getOrder)
router.post('/addquantity', isAuth,shopController.addQuantityCart)
router.get('/invoices/:orderId',isAuth,shopController.getInvoices)
module.exports = router